name: Linux Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  INSTALL_PATH: /home/runner/protobuf
  VERSION: 32.1
  
jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        unzip protobuf-32.1.0.zip
        mkdir ${{ env.INSTALL_PATH }}
        ./bin/protoc --version
        ./bin/protoc --cpp_out=${{ env.INSTALL_PATH }} widevine_protocol.proto
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Linux-artifact
        path: ${{ env.INSTALL_PATH }}
        if-no-files-found: ignore
        retention-days: 0
